language: java
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk6

script: mvn -DskipTests=true clean package

after_success:
  - bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
